######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 4 16:50:50 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += loc.h
SOURCES += loc.cpp main.cpp
CONFIG += mobility
MOBILITY += location
